package com.example.ui.recycler;

/**
 * Created by 傅令杰
 */

public enum MultipleFields {
    ITEM_TYPE,
    TITLE,
    TEXT,
    IMAGE_URL,
    BANNERS,
    SPAN_SIZE,
    ID,
    IDS,
    TEXTS,
    URLS,
    TITLES,
    NAME,
    TAG,
    ORGANIZATION_IMAGE_1,
    ORGANIZATION_IMAGE_2,
    CLASSNAME,
    CLASSINFO,
    AGE,
    ADDRESS,
    PHONE,
    DISTANCE,


    /**
     * 机构详情
     */
    HOME_ORGANIZATION_CLASS_NAME,
    HOME_ORGANIZATION_CLASS_BROWSE,
    HOME_ORGANIZATION_CLASS_LIKE,
    HOME_ORGANIZATION_CLASS_DISTANCE,

    HOME_ORGANIZATION_CLASS_ADDRESS,
    HOME_ORGANIZATION_CLASS_LONGITUDE,
    HOME_ORGANIZATION_CLASS_LATITUDE,

    HOME_ORGANIZATION_CLASS_INFO,
    HOME_ORGANIZATION_CLASS_COURSE,
    HOME_ORGANIZATION_CLASS_DISCOUNTS,

    HOME_ORGANIZATION_TEACHER_ID,
    HOME_ORGANIZATION_TEACHER_IMG,
    HOME_ORGANIZATION_TEACHER_INFO,

    HOME_ORGANIZATION_IMGLIST,
    HOME_ORGANIZATION_MOBILE,



}
