package com.example.ui.recycler;

/**
 * Created by 傅令杰
 */

public enum MultipleFields {
    ITEM_TYPE,
    TITLE,
    TEXT,
    IMAGE_URL,
    BANNERS,
    SPAN_SIZE,
    ID,
    IDS,
    TEXTS,
    URLS,
    TITLES,
    NAME,
    TAG,
    ORGANIZATION_IMAGE_1,
    ORGANIZATION_IMAGE_2,
    CLASSNAME,
    CLASSINFO,
    AGE,
    ADDRESS,
    PHONE,
    DISTANCE,


    /**
     * 机构详情
     */
    HOME_ORGANIZATION_CLASS_NAME,
    HOME_ORGANIZATION_CLASS_BROWSE,
    HOME_ORGANIZATION_CLASS_LIKE,
    HOME_ORGANIZATION_CLASS_DISTANCE,

    HOME_ORGANIZATION_CLASS_ADDRESS,
    HOME_ORGANIZATION_CLASS_LONGITUDE,
    HOME_ORGANIZATION_CLASS_LATITUDE,

    HOME_ORGANIZATION_CLASS_INFO,
    HOME_ORGANIZATION_CLASS_COURSE,
    HOME_ORGANIZATION_CLASS_TIME,
    HOME_ORGANIZATION_CLASS_DISCOUNTS,

    HOME_ORGANIZATION_TEACHER_ID,
    HOME_ORGANIZATION_TEACHER_IMG,
    HOME_ORGANIZATION_TEACHER_INFO,

    HOME_ORGANIZATION_IMGLIST,
    HOME_ORGANIZATION_MOBILE,
    HOME_ORGANIZATION_STATE,

    /**
     * 发现
     */
    DISCOVER_TEACHER_BANNERS,
    DISCOVER_TEACHER_IMG,
    DISCOVER_TEACHER_NAME,
    DISCOVER_TEACHER_INFO,
    DISCOVER_TEACHER_CLASS,
    DISCOVER_TEACHER_MOBILE,

    /**
     * 我的
     */
    PERSONAL_FOOTER_DATE,
    PERSONAL_FOOTER_ID,
    PERSONAL_FOOTER_HEATTARGET,
    PERSONAL_FOOTER_TARGERID,
    PERSONAL_FOOTER_IMG,
    PERSONAL_FOOTER_IS_DELETE,
    PERSONAL_FOOTER_IS_DELETE_ITEM,
    PERSONAL_FOOTER_SELECT_DELETE,
    PERSONAL_FOOTER_SELECT_DELETE_ITEM,

}
